project_id = "tduldxcqtizeiiluirnv"

[functions.fal-ai-generate]
verify_jwt = false

[functions.fal-ai-video]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
